
database:
    # the url where to find the database
    url: jdbc:mysql://localhost:3306/crowdcontrol
    #dialekt to use for communication
    dialect: MYSQL
    #the writing user
    writing:
        user: root
        password:
    #readonly user should really just be readonly
    readonly:
        user: root
        password:

#the defined platforms to run
platforms :
    # type to use
    #- type: mturk
      #standard credentials
    #  user: samplePlatformUser
    #  password: samplePassword
      #name which is used to display
    #  name: Sandbox
      # the url to give to the platform type
    #  url: fancySandboxUrl
    - type: dummy
      name: 1
      # dummy does not need any of the given fields
    - type: dummy
      name: 2
    - type: dummy
      name: 3