database:
    url: jdbc:mysql://localhost:3306/crowdcontrol?autoReconnect=true&useSSL=false
    dialect: MYSQL
    writing:
        user: root
        password:
    readonly:
        user: root
        password:

deployment:
    origin: http://localhost:3000
    workerService: http://worker.example.com
    workerUIPublic: http://worker.example.com

platforms :
    - type: dummy

mail:
    disabled: true

moneytransfer:
    payOffThreshold: 0
    parsingPassword: test
    notificationMailAddress: pseipd@gmail.com
    scheduleInterval: 7

jwtsecret: bGFtYWJhZGExMzY3OPxpbw==

log:
    com.zaxxer.hikari: WARN
    org.eclipse.jetty: WARN
    org.jooq.impl.DefaultBinding: WARN
    org.jooq.impl.DefaultConnectionProvider: WARN
    org.jooq.tools.StopWatch: WARN
    spark.webserver.MatcherFilter: WARN
    spark.Request: WARN