version: '2'
services:
  objectservice:
    image: coolcrowd/object-service:latest
    ports:
     - "4567:4567"
    depends_on:
     - db
    links:
     - db:db
    command:
      - -Dworkerservice.url=${DOCKERIP}:3333
  workerservice:
    image: coolcrowd/worker-service:latest
    ports:
      - "3333:4567"
    depends_on:
         - db
         - objectservice
    links:
         - db:db
         - objectservice:objectservice
    command:
            - -Ddatabase.url=jdbc:mysql://db
            - -Ddatabase.username=root
            - -Ddatabase.password=root
            - -Dos.url=http://objectservice:4567
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: crowdcontrol
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    command:
        - --character-set-server=utf8mb4
    ports:
         - "3306:3306"