version: '2'
services:
  controlui:
    extends:
        file: base.yml
        service: controlui

  objectservice:
    extends:
      file: base.yml
      service: objectservice
    links:
       - db:db
       - workerui:workerui
    depends_on:
       - db
       - workerui
    command:
      - -Dpybossa.disabled=true

  workerservice:
    extends:
      file: base.yml
      service: workerservice
    links:
       - db:db
       - objectservice:objectservice
    depends_on:
         - db
         - objectservice


  workerui:
    extends:
      file: base.yml
      service: workerui

  db:
     extends:
        file: base.yml
        service: db