version: '2'
services:
  objectservice:
    image: coolcrowd/object-service:docker
    ports:
     - "4567:4567"
    depends_on:
     - db
     - workerui
    links:
     - db:db
     - workerui:workerui
    command:
      - -Dworkerservice.url=http://${DOCKERIP}:3333
      - -Dworkerui.url=http://${DOCKERIP}:8080
      - -Dpybossa.disabled=true
  workerservice:
    image: coolcrowd/worker-service:latest
    ports:
      - "3333:4567"
    depends_on:
         - db
         - objectservice
    links:
         - db:db
         - objectservice:objectservice
    command:
            - -Ddatabase.url=jdbc:mysql://db
            - -Ddatabase.username=root
            - -Ddatabase.password=root
            - -Dos.url=http://objectservice:4567
  workerui:
      image: coolcrowd/worker-ui:latest
      ports:
        - "8080:80"
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: crowdcontrol
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    command:
        - --character-set-server=utf8mb4
    ports:
         - "3306:3306"